import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}


// 1. Establish Roles (not just colors)

// If you don’t assign roles, your UI will feel inconsistent.

// Primary (Brand Anchor)
// Red (#E52D2F) → main identity
// Use for:
// Primary CTA buttons (“Add to Cart”, “Order Now”)
// Highlights (badges, promos)
// Rule: never background the whole page with this
// Secondary (Energy / Accent)
// Yellow (#FFC107) → attention grabber
// Use for:
// Price tags
// Discounts
// Hover states
// Rule: small doses only or it becomes noisy
// Support (Fresh / Category)
// Green (#2E7D32) → “fresh”, “new”, “healthy”
// Use for:
// Labels like “New”, “Fresh”
// Category indicators
// 2. Control the Base (This is where most people fail)

// If your base is loud, everything breaks.

// Backgrounds
// #FFF9F0 (off-white) → main background
// #111827 (dark) → header/footer or sections

// Why?

// Your logo is already busy → you need calm surfaces
// 3. Build a Clear UI Hierarchy
// Buttons
// Primary: Red background + white text
// Secondary: White background + red border
// Tertiary: Text-only (dark gray)

// If every button is red → nothing stands out.

// Cards (Products)
// White card
// Soft shadow
// Yellow for price
// Red ONLY for “Add to cart”

// Don’t:

// ❌ Color entire cards red/yellow
// ❌ Mix gradients everywhere
// Navigation
// Dark background (#111827)
// White text
// Red underline or active state

// This keeps it premium instead of “toy store chaos.”

// 4. Color Distribution Rule (steal this, don’t improvise)

// Use 60–30–10 rule:

// 60% → neutral (white/off-white)
// 30% → dark (text, headers)
// 10% → brand colors (red/yellow/green)

// If your brand colors exceed 15–20%, your UI becomes exhausting.

// 5. Interaction System (this separates amateurs from pros)

// Define states:

// Hover:
// Red → darker red
// Yellow → slightly deeper gold
// Active:
// Slight scale down + darker shade
// Disabled:
// Gray everything (don’t use faded red)

// Consistency > creativity.

// 6. Typography Strategy (don’t mess this up)

// You were given:

// Baloo 2 (headings)
// Poppins (body)

// Here’s the reality:

// Baloo is very playful
// If you use it everywhere → childish, not retail
// Correct usage:
// Baloo → logo, big headings only
// Poppins → everything else
// 7. Layout Strategy (critical for your K-mart idea)

// Your site should feel like:

// Fast
// Clear
// Easy to scan

// So:

// Big search bar (top priority)
// Category chips (use green/yellow subtly)
// Grid products
// Sticky cart button (red)
// 8. Common Mistakes I expect you’ll make (don’t)
// ❌ Using gradients everywhere because logo has gradient
// ❌ Yellow text on white (low contrast)
// ❌ Red background + yellow text (visual noise)
// ❌ No spacing → everything feels cramped
// ❌ Overusing shadows
// 9. If you want this to feel legit (not student project)

// Add:

// Subtle animations (hover lift, button press)
// Consistent spacing system (8px scale)
// Real product hierarchy (don’t treat all items equally)
// Brutal truth

// Right now your brand direction is high energy but risky.
// If you don’t control color usage, your site will look like a cheap flyer instead of a real store.

// If you want, I can:

// Break this into a Tailwind config (colors + tokens)
// Or 
// design your homepage layout structure (production-level, not generic)